In [27]:
import numpy as np

In [28]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [29]:
a[1,5]

13

In [30]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [31]:
a[:,2]

array([ 3, 10])

In [32]:
a[0,1:-1:2]

array([2, 4, 6])

In [33]:
a[1,5]=20
print(a)
a[:,2]=5
print(a)
a[:,2]=[1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [34]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [35]:
b[0,1,1]

4

In [36]:
b[:,1,:]=[[9,9],[9,9]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [9 9]]]


In [37]:
a[1,5]=20
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
