In [181]:
import numpy as np

In [182]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [183]:
np.ones((2,3,3,2))

array([[[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]]])

In [184]:
np.full((2,2),99,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [185]:
a=np.array([[1,2,3,4,5],[6,7,8,9,0]])

In [186]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [187]:
np.random.rand(4,2)

array([[0.6253078 , 0.18922619],
       [0.16283709, 0.35456129],
       [0.77600567, 0.74998156],
       [0.42599031, 0.88390933]])

In [188]:
np.random.random_sample(a.shape)

array([[0.07310341, 0.12736946, 0.06842372, 0.76243812, 0.5299864 ],
       [0.10912138, 0.72894854, 0.00629664, 0.59650974, 0.37160639]])

In [189]:
np.random.randint(4,7,size=(3,3))

array([[5, 6, 5],
       [4, 4, 5],
       [6, 6, 4]])

In [190]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [191]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [192]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [203]:
output=np.ones((5,5))
z=np.zeros((3,3))
print(output)
z[1,1]=9
print(z)
output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
