In [31]:
import numpy as np

In [32]:
a=np.array([1,2,3])
print (a)

[1 2 3]


In [33]:
print (a)

[1 2 3]


In [43]:
a=np.array([1,2,3],dtype='int32')
print (a)

[1 2 3]


In [35]:
b=np.array([[1.2,2,3],[1.3,2,3],[1.4,2,3]])
print (b)

[[1.2 2.  3. ]
 [1.3 2.  3. ]
 [1.4 2.  3. ]]


In [36]:
a.ndim

1

In [37]:
b.shape

(3, 3)

In [38]:
#get type
a.dtype

dtype('int32')

In [39]:
a.itemsize
b.itemsize

8

In [40]:
a.itemsize

4